import type {
  SettingDomain,
  SettingRegistryEntry,
  SettingValueType,
  SettingVisibility,
} from '../../../shared/types/index.js';

interface SettingRegistryInput {
  key: string;
  label: string;
  domain: SettingDomain;
  visibility: SettingVisibility;
  valueType: SettingValueType;
  description: string;
  uiPages?: string[];
  runtimeConsumers?: string[];
  sourceOrder?: string[];
}

function defineSetting(input: SettingRegistryInput): SettingRegistryEntry {
  return {
    key: input.key,
    label: input.label,
    domain: input.domain,
    visibility: input.visibility,
    valueType: input.valueType,
    description: input.description,
    uiPages: input.uiPages ?? [],
    runtimeConsumers: input.runtimeConsumers ?? [],
    sourceOrder: input.sourceOrder ?? ['db'],
  };
}

export const SETTINGS_REGISTRY: SettingRegistryEntry[] = [
  defineSetting({
    key: 'telegram_bot_token',
    label: 'Telegram Bot Token',
    domain: 'api_keys',
    visibility: 'visible',
    valueType: 'secret',
    description: 'Токен Telegram бота, используется при старте если env пуст.',
    uiPages: ['ApiKeysPage'],
    runtimeConsumers: ['bot/src/index.ts'],
    sourceOrder: ['env', 'db'],
  }),
  defineSetting({
    key: 'openrouter_api_key',
    label: 'OpenRouter API Key',
    domain: 'api_keys',
    visibility: 'visible',
    valueType: 'secret',
    description: 'Главный ключ для chat/image/search fallback runtime.',
    uiPages: ['ApiKeysPage'],
    runtimeConsumers: ['bot/src/config/index.ts', 'bot/src/ai/openrouter.ts', 'bot/src/ai/image-gen.ts', 'bot/src/ai/websearch.ts'],
    sourceOrder: ['env', 'db'],
  }),
  defineSetting({
    key: 'groq_api_key',
    label: 'Groq API Key',
    domain: 'api_keys',
    visibility: 'visible',
    valueType: 'secret',
    description: 'Ключ Groq для аудио-транскрипции и классификаторов.',
    uiPages: ['ApiKeysPage'],
    runtimeConsumers: ['bot/src/config/index.ts', 'bot/src/ai/multimodal.ts', 'bot/src/ai/image-gen.ts'],
    sourceOrder: ['env', 'db'],
  }),
  defineSetting({
    key: 'perplexity_api_key',
    label: 'Perplexity API Key',
    domain: 'api_keys',
    visibility: 'visible',
    valueType: 'secret',
    description: 'Ключ Perplexity для web search runtime.',
    uiPages: ['ApiKeysPage'],
    runtimeConsumers: ['bot/src/ai/websearch.ts'],
    sourceOrder: ['env', 'db'],
  }),
  defineSetting({
    key: 'llm_verify_enabled',
    label: 'LLM Verify Enabled',
    domain: 'api_keys',
    visibility: 'deprecated',
    valueType: 'boolean',
    description: 'Историческое поле UI. Сейчас runtime его не читает напрямую.',
    uiPages: ['ApiKeysPage'],
    runtimeConsumers: [],
    sourceOrder: ['db'],
  }),
  defineSetting({
    key: 'web_search_enabled',
    label: 'Web Search Enabled',
    domain: 'api_keys',
    visibility: 'visible',
    valueType: 'boolean',
    description: 'Явный флаг web search; при отсутствии применяется auto-detect.',
    uiPages: ['ApiKeysPage'],
    runtimeConsumers: ['bot/src/ai/websearch.ts'],
    sourceOrder: ['db', 'derived'],
  }),
  defineSetting({
    key: 'perplexity_model',
    label: 'Perplexity Model',
    domain: 'api_keys',
    visibility: 'visible',
    valueType: 'string',
    description: 'Модель поиска Perplexity.',
    uiPages: ['ApiKeysPage'],
    runtimeConsumers: ['bot/src/ai/websearch.ts'],
  }),
  defineSetting({
    key: 'web_search_max_tokens',
    label: 'Web Search Max Tokens',
    domain: 'api_keys',
    visibility: 'visible',
    valueType: 'number',
    description: 'Лимит токенов для search answers.',
    uiPages: ['ApiKeysPage'],
    runtimeConsumers: ['bot/src/ai/websearch.ts'],
  }),
  defineSetting({
    key: 'ai_provider',
    label: 'AI Provider',
    domain: 'chat',
    visibility: 'visible',
    valueType: 'string',
    description: 'Выбор главного chat provider: auto, lmstudio или openrouter.',
    uiPages: ['SettingsPage', 'LMStudioPage'],
    runtimeConsumers: ['bot/src/ai/lmstudio.ts', 'bot/src/ai/openrouter.ts'],
    sourceOrder: ['db', 'default'],
  }),
  defineSetting({
    key: 'openrouter_model',
    label: 'OpenRouter Model',
    domain: 'chat',
    visibility: 'visible',
    valueType: 'string',
    description: 'Базовая chat model OpenRouter.',
    uiPages: ['SettingsPage'],
    runtimeConsumers: ['bot/src/ai/openrouter.ts', 'bot/src/ai/websearch.ts'],
    sourceOrder: ['db', 'env', 'default'],
  }),
  defineSetting({
    key: 'custom_model_override',
    label: 'Custom Model Override',
    domain: 'chat',
    visibility: 'visible',
    valueType: 'string',
    description: 'Явный override для chat model поверх openrouter_model.',
    uiPages: ['SettingsPage'],
    runtimeConsumers: ['bot/src/ai/openrouter.ts'],
    sourceOrder: ['db'],
  }),
  defineSetting({
    key: 'max_tokens',
    label: 'Max Tokens',
    domain: 'chat',
    visibility: 'visible',
    valueType: 'number',
    description: 'Глобальный токен-лимит chat runtime.',
    uiPages: ['SettingsPage'],
    runtimeConsumers: ['bot/src/ai/openrouter.ts', 'bot/src/ai/multimodal.ts'],
  }),
  defineSetting({
    key: 'temperature',
    label: 'Temperature',
    domain: 'chat',
    visibility: 'visible',
    valueType: 'number',
    description: 'Температура генерации chat runtime.',
    uiPages: ['SettingsPage'],
    runtimeConsumers: ['bot/src/ai/openrouter.ts'],
  }),
  defineSetting({
    key: 'preferred_vision_model',
    label: 'Preferred Vision Model',
    domain: 'multimodal',
    visibility: 'visible',
    valueType: 'string',
    description: 'Ручной выбор администратора для vision runtime.',
    uiPages: ['MultimodalSettingsPage'],
    runtimeConsumers: ['bot/src/ai/multimodal.ts', 'bot/src/ai/effective-capabilities.ts'],
  }),
  defineSetting({
    key: 'effective_vision_model',
    label: 'Effective Vision Model',
    domain: 'multimodal',
    visibility: 'derived',
    valueType: 'string',
    description: 'Фактическая рабочая vision модель runtime после fallback.',
    uiPages: ['MultimodalSettingsPage', 'SelfCorePage'],
    runtimeConsumers: ['bot/src/ai/multimodal.ts', 'bot/src/ai/effective-capabilities.ts'],
    sourceOrder: ['runtime', 'db'],
  }),
  defineSetting({
    key: 'vision_model',
    label: 'Legacy Vision Model',
    domain: 'multimodal',
    visibility: 'deprecated',
    valueType: 'string',
    description: 'Исторический ключ vision model, сохранён для миграционной совместимости.',
    uiPages: [],
    runtimeConsumers: ['bot/src/ai/multimodal.ts', 'bot/src/ai/effective-capabilities.ts'],
  }),
  defineSetting({
    key: 'vision_model_override',
    label: 'Vision Model Override',
    domain: 'multimodal',
    visibility: 'internal',
    valueType: 'string',
    description: 'Скрытый override vision runtime поверх preferred/effective state.',
    uiPages: ['SelfCorePage'],
    runtimeConsumers: ['bot/src/ai/multimodal.ts', 'bot/src/ai/effective-capabilities.ts'],
  }),
  defineSetting({
    key: 'audio_model',
    label: 'Audio Model',
    domain: 'multimodal',
    visibility: 'visible',
    valueType: 'string',
    description: 'Базовая модель аудио-транскрипции.',
    uiPages: ['MultimodalSettingsPage'],
    runtimeConsumers: ['bot/src/ai/multimodal.ts', 'bot/src/ai/effective-capabilities.ts'],
  }),
  defineSetting({
    key: 'audio_model_override',
    label: 'Audio Model Override',
    domain: 'multimodal',
    visibility: 'internal',
    valueType: 'string',
    description: 'Скрытый override audio runtime.',
    uiPages: ['SelfCorePage'],
    runtimeConsumers: ['bot/src/ai/multimodal.ts', 'bot/src/ai/effective-capabilities.ts'],
  }),
  defineSetting({
    key: 'vision_prompt',
    label: 'Vision Prompt',
    domain: 'multimodal',
    visibility: 'visible',
    valueType: 'string',
    description: 'Базовый prompt для описания изображений.',
    uiPages: ['MultimodalSettingsPage'],
    runtimeConsumers: ['bot/src/ai/multimodal.ts'],
  }),
  defineSetting({
    key: 'vision_max_tokens',
    label: 'Vision Max Tokens',
    domain: 'multimodal',
    visibility: 'visible',
    valueType: 'number',
    description: 'Максимум токенов для ответа vision runtime.',
    uiPages: ['MultimodalSettingsPage'],
    runtimeConsumers: ['bot/src/ai/multimodal.ts'],
  }),
  defineSetting({
    key: 'hf_token',
    label: 'HuggingFace Token',
    domain: 'multimodal',
    visibility: 'internal',
    valueType: 'secret',
    description: 'Токен HuggingFace для image generation fallback.',
    uiPages: ['SelfCorePage'],
    runtimeConsumers: ['bot/src/ai/image-gen.ts', 'bot/src/ai/effective-capabilities.ts'],
  }),
  defineSetting({
    key: 'openrouter_image_model',
    label: 'OpenRouter Image Model',
    domain: 'multimodal',
    visibility: 'visible',
    valueType: 'string',
    description: 'Модель генерации изображений через OpenRouter.',
    uiPages: ['MultimodalSettingsPage'],
    runtimeConsumers: ['bot/src/ai/image-gen.ts', 'bot/src/ai/effective-capabilities.ts'],
  }),
  defineSetting({
    key: 'tts_enabled',
    label: 'TTS Enabled',
    domain: 'tts',
    visibility: 'visible',
    valueType: 'boolean',
    description: 'Главный переключатель TTS runtime. Если false, синтез речи отключается во всех путях.',
    uiPages: ['MultimodalSettingsPage', 'SelfCorePage'],
    runtimeConsumers: ['bot/src/features/tts.ts', 'bot/src/ai/effective-capabilities.ts'],
  }),
  defineSetting({
    key: 'tts_provider',
    label: 'TTS Provider',
    domain: 'tts',
    visibility: 'visible',
    valueType: 'string',
    description: 'Выбранный движок синтеза речи.',
    uiPages: ['MultimodalSettingsPage'],
    runtimeConsumers: ['bot/src/features/tts.ts', 'bot/src/ai/effective-capabilities.ts'],
  }),
  defineSetting({
    key: 'elevenlabs_api_key',
    label: 'ElevenLabs API Key',
    domain: 'tts',
    visibility: 'visible',
    valueType: 'secret',
    description: 'Ключ ElevenLabs для премиального TTS.',
    uiPages: ['MultimodalSettingsPage'],
    runtimeConsumers: ['bot/src/features/tts.ts', 'bot/src/ai/effective-capabilities.ts'],
  }),
  defineSetting({
    key: 'elevenlabs_voice_id',
    label: 'ElevenLabs Voice ID',
    domain: 'tts',
    visibility: 'visible',
    valueType: 'string',
    description: 'Финальный voice id для ElevenLabs.',
    uiPages: ['MultimodalSettingsPage'],
    runtimeConsumers: ['bot/src/features/tts.ts'],
  }),
  defineSetting({
    key: 'elevenlabs_custom_voice_id',
    label: 'ElevenLabs Custom Voice ID',
    domain: 'tts',
    visibility: 'deprecated',
    valueType: 'string',
    description: 'UI-helper поле, не читается runtime напрямую.',
    uiPages: ['MultimodalSettingsPage'],
    runtimeConsumers: [],
  }),
  defineSetting({
    key: 'elevenlabs_model_id',
    label: 'ElevenLabs Model ID',
    domain: 'tts',
    visibility: 'visible',
    valueType: 'string',
    description: 'Модель ElevenLabs для синтеза речи.',
    uiPages: ['MultimodalSettingsPage'],
    runtimeConsumers: ['bot/src/features/tts.ts'],
  }),
  defineSetting({
    key: 'openai_api_key',
    label: 'OpenAI API Key',
    domain: 'tts',
    visibility: 'visible',
    valueType: 'secret',
    description: 'Ключ OpenAI для TTS.',
    uiPages: ['MultimodalSettingsPage'],
    runtimeConsumers: ['bot/src/features/tts.ts', 'bot/src/ai/effective-capabilities.ts'],
  }),
  defineSetting({
    key: 'openai_tts_voice',
    label: 'OpenAI TTS Voice',
    domain: 'tts',
    visibility: 'visible',
    valueType: 'string',
    description: 'Голос OpenAI TTS.',
    uiPages: ['MultimodalSettingsPage'],
    runtimeConsumers: ['bot/src/features/tts.ts'],
  }),
  defineSetting({
    key: 'openai_tts_model',
    label: 'OpenAI TTS Model',
    domain: 'tts',
    visibility: 'visible',
    valueType: 'string',
    description: 'Модель OpenAI TTS.',
    uiPages: ['MultimodalSettingsPage'],
    runtimeConsumers: ['bot/src/features/tts.ts', 'bot/src/ai/effective-capabilities.ts'],
  }),
  defineSetting({
    key: 'voice_speaker',
    label: 'Edge Voice Speaker',
    domain: 'tts',
    visibility: 'visible',
    valueType: 'string',
    description: 'Выбранный голос Edge TTS.',
    uiPages: ['MultimodalSettingsPage'],
    runtimeConsumers: ['bot/src/features/tts.ts'],
  }),
  defineSetting({
    key: 'persona_name',
    label: 'Persona Name',
    domain: 'persona',
    visibility: 'visible',
    valueType: 'string',
    description: 'Имя сущности Amina.',
    uiPages: ['PersonaPage'],
    runtimeConsumers: ['bot/src/ai/persona.ts', 'bot/src/ai/self-core.ts'],
  }),
  defineSetting({
    key: 'persona_identity',
    label: 'Persona Identity',
    domain: 'persona',
    visibility: 'visible',
    valueType: 'string',
    description: 'Основная идентичность Amina.',
    uiPages: ['PersonaPage'],
    runtimeConsumers: ['bot/src/ai/persona.ts', 'bot/src/ai/self-core.ts'],
  }),
  defineSetting({
    key: 'persona_relationship_to_owner',
    label: 'Persona Relationship To Owner',
    domain: 'persona',
    visibility: 'visible',
    valueType: 'string',
    description: 'Каноническая связь Amina с владельцем.',
    uiPages: ['PersonaPage'],
    runtimeConsumers: ['bot/src/ai/persona.ts', 'bot/src/ai/self-core.ts'],
  }),
  defineSetting({
    key: 'persona_owner_title',
    label: 'Persona Owner Title',
    domain: 'persona',
    visibility: 'visible',
    valueType: 'string',
    description: 'Имя или титул владельца.',
    uiPages: ['PersonaPage'],
    runtimeConsumers: ['bot/src/ai/persona.ts', 'bot/src/ai/self-core.ts'],
  }),
  defineSetting({
    key: 'persona_style_intensity',
    label: 'Persona Style Intensity',
    domain: 'persona',
    visibility: 'visible',
    valueType: 'number',
    description: 'Интенсивность ритуального стиля.',
    uiPages: ['PersonaPage'],
    runtimeConsumers: ['bot/src/ai/persona.ts'],
  }),
  defineSetting({
    key: 'persona_ritual_lexicon',
    label: 'Persona Ritual Lexicon',
    domain: 'persona',
    visibility: 'visible',
    valueType: 'string',
    description: 'Ритуальный лексикон образа.',
    uiPages: ['PersonaPage'],
    runtimeConsumers: ['bot/src/ai/persona.ts'],
  }),
  defineSetting({
    key: 'persona_forbidden_phrases',
    label: 'Persona Forbidden Phrases',
    domain: 'persona',
    visibility: 'visible',
    valueType: 'string',
    description: 'Запретные фразы образа.',
    uiPages: ['PersonaPage'],
    runtimeConsumers: ['bot/src/ai/persona.ts'],
  }),
  defineSetting({
    key: 'persona_channel_telegram',
    label: 'Persona Telegram Channel',
    domain: 'persona',
    visibility: 'visible',
    valueType: 'string',
    description: 'Persona-вариант для Telegram.',
    uiPages: ['PersonaPage'],
    runtimeConsumers: ['bot/src/ai/persona.ts'],
  }),
  defineSetting({
    key: 'persona_channel_voice',
    label: 'Persona Voice Channel',
    domain: 'persona',
    visibility: 'visible',
    valueType: 'string',
    description: 'Persona-вариант для voice.',
    uiPages: ['PersonaPage'],
    runtimeConsumers: ['bot/src/ai/persona.ts'],
  }),
  defineSetting({
    key: 'persona_channel_digest',
    label: 'Persona Digest Channel',
    domain: 'persona',
    visibility: 'visible',
    valueType: 'string',
    description: 'Persona-вариант для digest.',
    uiPages: ['PersonaPage'],
    runtimeConsumers: ['bot/src/ai/persona.ts'],
  }),
  defineSetting({
    key: 'persona_channel_system',
    label: 'Persona System Channel',
    domain: 'persona',
    visibility: 'visible',
    valueType: 'string',
    description: 'Persona-вариант для system tasks.',
    uiPages: ['PersonaPage'],
    runtimeConsumers: ['bot/src/ai/persona.ts'],
  }),
  defineSetting({
    key: 'persona_self_lives_by',
    label: 'Persona Self Lives By',
    domain: 'persona',
    visibility: 'visible',
    valueType: 'string',
    description: 'Self-disclosure: чем живёт Amina.',
    uiPages: ['PersonaPage'],
    runtimeConsumers: ['bot/src/ai/persona.ts'],
  }),
  defineSetting({
    key: 'persona_self_loves',
    label: 'Persona Self Loves',
    domain: 'persona',
    visibility: 'visible',
    valueType: 'string',
    description: 'Self-disclosure: что любит Amina.',
    uiPages: ['PersonaPage'],
    runtimeConsumers: ['bot/src/ai/persona.ts'],
  }),
  defineSetting({
    key: 'persona_self_relates_to_owner',
    label: 'Persona Self Relates To Owner',
    domain: 'persona',
    visibility: 'visible',
    valueType: 'string',
    description: 'Self-disclosure: как Amina относится к владельцу.',
    uiPages: ['PersonaPage'],
    runtimeConsumers: ['bot/src/ai/persona.ts'],
  }),
  defineSetting({
    key: 'persona_self_flirt_response',
    label: 'Persona Self Flirt Response',
    domain: 'persona',
    visibility: 'visible',
    valueType: 'string',
    description: 'Self-disclosure: реакция на флирт.',
    uiPages: ['PersonaPage'],
    runtimeConsumers: ['bot/src/ai/persona.ts'],
  }),
  defineSetting({
    key: 'persona_self_intro_short',
    label: 'Persona Self Intro Short',
    domain: 'persona',
    visibility: 'visible',
    valueType: 'string',
    description: 'Короткое self-intro Amina.',
    uiPages: ['PersonaPage'],
    runtimeConsumers: ['bot/src/ai/persona.ts'],
  }),
  defineSetting({
    key: 'persona_self_intro_warm',
    label: 'Persona Self Intro Warm',
    domain: 'persona',
    visibility: 'visible',
    valueType: 'string',
    description: 'Тёплое self-intro Amina.',
    uiPages: ['PersonaPage'],
    runtimeConsumers: ['bot/src/ai/persona.ts'],
  }),
  defineSetting({
    key: 'admin_chat_id',
    label: 'Admin Chat ID',
    domain: 'telephony',
    visibility: 'visible',
    valueType: 'string',
    description: 'Глобальный admin chat id для уведомлений.',
    uiPages: ['TelephonyPage'],
    runtimeConsumers: ['bot/src/features/telephony/service/telephony-runtime-config.ts', 'bot/src/api/routes/news.ts'],
    sourceOrder: ['db', 'env'],
  }),
  defineSetting({
    key: 'lirax_admin_chat_id',
    label: 'LiraX Admin Chat ID',
    domain: 'telephony',
    visibility: 'visible',
    valueType: 'string',
    description: 'Admin chat id, специфичный для telephony.',
    uiPages: ['TelephonyPage'],
    runtimeConsumers: ['bot/src/features/telephony/service/telephony-runtime-config.ts', 'bot/src/features/telephony/lirax.ts'],
    sourceOrder: ['db', 'db(admin_chat_id)', 'env'],
  }),
  defineSetting({
    key: 'lirax_owner_chat_id',
    label: 'LiraX Owner Chat ID',
    domain: 'telephony',
    visibility: 'visible',
    valueType: 'string',
    description: 'Owner chat id для telephony summary и alerts.',
    uiPages: ['TelephonyPage'],
    runtimeConsumers: ['bot/src/features/telephony/service/telephony-runtime-config.ts', 'bot/src/features/telephony/ai-scenarios.ts'],
    sourceOrder: ['db', 'db(lirax_admin_chat_id)', 'db(admin_chat_id)', 'env'],
  }),
  defineSetting({
    key: 'lirax_url',
    label: 'LiraX URL',
    domain: 'telephony',
    visibility: 'visible',
    valueType: 'string',
    description: 'Base URL LiraX API.',
    uiPages: ['TelephonyPage'],
    runtimeConsumers: ['bot/src/features/telephony/service/telephony-runtime-config.ts', 'bot/src/features/telephony/lirax.ts'],
    sourceOrder: ['db', 'env', 'default'],
  }),
  defineSetting({
    key: 'lirax_token',
    label: 'LiraX Token',
    domain: 'telephony',
    visibility: 'visible',
    valueType: 'secret',
    description: 'LiraX auth token.',
    uiPages: ['TelephonyPage'],
    runtimeConsumers: ['bot/src/features/telephony/service/telephony-runtime-config.ts', 'bot/src/features/telephony/lirax.ts'],
    sourceOrder: ['db', 'env'],
  }),
  defineSetting({
    key: 'lirax_webhook_token',
    label: 'LiraX Webhook Token',
    domain: 'telephony',
    visibility: 'visible',
    valueType: 'secret',
    description: 'Токен проверки входящих LiraX webhook.',
    uiPages: ['TelephonyPage'],
    runtimeConsumers: ['bot/src/features/telephony/service/telephony-runtime-config.ts', 'bot/src/features/telephony/lirax.ts'],
    sourceOrder: ['db', 'env'],
  }),
  defineSetting({
    key: 'lirax_default_ext',
    label: 'LiraX Default Ext',
    domain: 'telephony',
    visibility: 'visible',
    valueType: 'string',
    description: 'Default extension для исходящих вызовов.',
    uiPages: ['TelephonyPage'],
    runtimeConsumers: ['bot/src/features/telephony/service/telephony-runtime-config.ts'],
    sourceOrder: ['db', 'env', 'default'],
  }),
  defineSetting({
    key: 'lirax_operator_phone',
    label: 'LiraX Operator Phone',
    domain: 'telephony',
    visibility: 'visible',
    valueType: 'string',
    description: 'Operator phone для telephony runtime.',
    uiPages: ['TelephonyPage'],
    runtimeConsumers: ['bot/src/features/telephony/service/telephony-runtime-config.ts'],
    sourceOrder: ['db', 'env'],
  }),
  defineSetting({
    key: 'lirax_notify_calls',
    label: 'LiraX Notify Calls',
    domain: 'telephony',
    visibility: 'visible',
    valueType: 'boolean',
    description: 'Флаг уведомлений о звонках.',
    uiPages: ['TelephonyPage'],
    runtimeConsumers: ['bot/src/api/routes/telephony.ts', 'bot/src/features/telephony/service/telephony-runtime-config.ts'],
    sourceOrder: ['db', 'env', 'default'],
  }),
  defineSetting({
    key: 'lirax_notify_records',
    label: 'LiraX Notify Records',
    domain: 'telephony',
    visibility: 'visible',
    valueType: 'boolean',
    description: 'Флаг уведомлений о записях звонков.',
    uiPages: ['TelephonyPage'],
    runtimeConsumers: ['bot/src/api/routes/telephony.ts', 'bot/src/features/telephony/service/telephony-runtime-config.ts'],
    sourceOrder: ['db', 'env', 'default'],
  }),
  defineSetting({
    key: 'telephony_realtime_enabled',
    label: 'Telephony Realtime Enabled',
    domain: 'telephony',
    visibility: 'visible',
    valueType: 'boolean',
    description: 'Глобальное включение realtime voice режима.',
    uiPages: ['TelephonyPage'],
    runtimeConsumers: ['bot/src/features/telephony/service/telephony-runtime-config.ts'],
    sourceOrder: ['db', 'env', 'default'],
  }),
  defineSetting({
    key: 'telephony_media_bridge_url',
    label: 'Telephony Media Bridge URL',
    domain: 'telephony',
    visibility: 'visible',
    valueType: 'string',
    description: 'URL media bridge для realtime voice.',
    uiPages: ['TelephonyPage'],
    runtimeConsumers: ['bot/src/features/telephony/service/telephony-runtime-config.ts'],
    sourceOrder: ['db', 'env'],
  }),
  defineSetting({
    key: 'telephony_media_bridge_token',
    label: 'Telephony Media Bridge Token',
    domain: 'telephony',
    visibility: 'visible',
    valueType: 'secret',
    description: 'Токен media bridge.',
    uiPages: ['TelephonyPage'],
    runtimeConsumers: ['bot/src/features/telephony/service/telephony-runtime-config.ts'],
    sourceOrder: ['db', 'env'],
  }),
  defineSetting({
    key: 'telephony_media_bridge_health_url',
    label: 'Telephony Media Bridge Health URL',
    domain: 'telephony',
    visibility: 'internal',
    valueType: 'string',
    description: 'Derived или explicit health URL media bridge.',
    uiPages: ['SelfCorePage'],
    runtimeConsumers: ['bot/src/features/telephony/service/telephony-runtime-config.ts'],
    sourceOrder: ['db', 'env', 'derived'],
  }),
  defineSetting({
    key: 'telephony_recordings_archive_enabled',
    label: 'Telephony Recordings Archive Enabled',
    domain: 'telephony',
    visibility: 'visible',
    valueType: 'boolean',
    description: 'Флаг архивации записей звонков.',
    uiPages: ['TelephonyPage'],
    runtimeConsumers: ['bot/src/features/telephony/service/telephony-runtime-config.ts'],
    sourceOrder: ['db', 'env', 'default'],
  }),
  defineSetting({
    key: 'telephony_partial_transcript_enabled',
    label: 'Telephony Partial Transcript Enabled',
    domain: 'telephony',
    visibility: 'visible',
    valueType: 'boolean',
    description: 'Флаг хранения partial transcript.',
    uiPages: ['TelephonyPage'],
    runtimeConsumers: ['bot/src/features/telephony/service/telephony-runtime-config.ts'],
    sourceOrder: ['db', 'env', 'default'],
  }),
  defineSetting({
    key: 'telephony_latency_budget_ms',
    label: 'Telephony Latency Budget',
    domain: 'telephony',
    visibility: 'visible',
    valueType: 'number',
    description: 'Latency budget realtime voice.',
    uiPages: ['TelephonyPage'],
    runtimeConsumers: ['bot/src/features/telephony/service/telephony-runtime-config.ts'],
    sourceOrder: ['db', 'env', 'default'],
  }),
  defineSetting({
    key: 'telephony_recording_retention_days',
    label: 'Telephony Recording Retention Days',
    domain: 'telephony',
    visibility: 'visible',
    valueType: 'number',
    description: 'Retention дней для записей.',
    uiPages: ['TelephonyPage'],
    runtimeConsumers: ['bot/src/features/telephony/service/telephony-runtime-config.ts'],
    sourceOrder: ['db', 'env', 'default'],
  }),
  defineSetting({
    key: 'telephony_sip_server',
    label: 'Telephony SIP Server',
    domain: 'telephony',
    visibility: 'visible',
    valueType: 'string',
    description: 'SIP server для внешней телефонии.',
    uiPages: ['TelephonyPage'],
    runtimeConsumers: ['bot/src/features/telephony/service/telephony-runtime-config.ts'],
    sourceOrder: ['db', 'env'],
  }),
  defineSetting({
    key: 'telephony_sip_login',
    label: 'Telephony SIP Login',
    domain: 'telephony',
    visibility: 'visible',
    valueType: 'string',
    description: 'Логин SIP.',
    uiPages: ['TelephonyPage'],
    runtimeConsumers: ['bot/src/features/telephony/service/telephony-runtime-config.ts'],
    sourceOrder: ['db', 'env'],
  }),
  defineSetting({
    key: 'telephony_sip_password',
    label: 'Telephony SIP Password',
    domain: 'telephony',
    visibility: 'visible',
    valueType: 'secret',
    description: 'Пароль SIP.',
    uiPages: ['TelephonyPage'],
    runtimeConsumers: ['bot/src/features/telephony/service/telephony-runtime-config.ts'],
    sourceOrder: ['db', 'env'],
  }),
  defineSetting({
    key: 'telephony_external_number',
    label: 'Telephony External Number',
    domain: 'telephony',
    visibility: 'visible',
    valueType: 'string',
    description: 'Внешний номер телефонии.',
    uiPages: ['TelephonyPage'],
    runtimeConsumers: ['bot/src/features/telephony/service/telephony-runtime-config.ts'],
    sourceOrder: ['db', 'env'],
  }),
  defineSetting({
    key: 'telephony_ai_provider',
    label: 'Telephony AI Provider',
    domain: 'telephony',
    visibility: 'visible',
    valueType: 'string',
    description: 'Provider voice-runtime: inherit, openrouter, lmstudio.',
    uiPages: ['TelephonyPage'],
    runtimeConsumers: ['bot/src/features/telephony/service/telephony-runtime-config.ts', 'bot/src/ai/openrouter.ts'],
    sourceOrder: ['db', 'env', 'default'],
  }),
  defineSetting({
    key: 'telephony_openrouter_model',
    label: 'Telephony OpenRouter Model',
    domain: 'telephony',
    visibility: 'visible',
    valueType: 'string',
    description: 'Отдельная модель для voice runtime.',
    uiPages: ['TelephonyPage'],
    runtimeConsumers: ['bot/src/features/telephony/service/telephony-runtime-config.ts', 'bot/src/ai/openrouter.ts'],
    sourceOrder: ['db', 'env'],
  }),
  defineSetting({
    key: 'telephony_allowed_users',
    label: 'Telephony Allowed Users',
    domain: 'telephony',
    visibility: 'internal',
    valueType: 'json',
    description: 'JSON ACL для telephony доступа.',
    uiPages: ['TelephonyPage'],
    runtimeConsumers: ['bot/src/features/telephony/lirax.ts'],
  }),
  defineSetting({
    key: 'lmstudio_url',
    label: 'LM Studio URL',
    domain: 'lmstudio',
    visibility: 'visible',
    valueType: 'string',
    description: 'Базовый URL LM Studio или tunnel endpoint.',
    uiPages: ['LMStudioPage'],
    runtimeConsumers: ['bot/src/ai/lmstudio.ts', 'bot/src/api/routes/middleware.ts'],
  }),
  defineSetting({
    key: 'lmstudio_model',
    label: 'LM Studio Model',
    domain: 'lmstudio',
    visibility: 'visible',
    valueType: 'string',
    description: 'Модель LM Studio.',
    uiPages: ['LMStudioPage'],
    runtimeConsumers: ['bot/src/ai/lmstudio.ts'],
  }),
  defineSetting({
    key: 'lmstudio_api_key',
    label: 'LM Studio API Key',
    domain: 'lmstudio',
    visibility: 'visible',
    valueType: 'secret',
    description: 'API key LM Studio.',
    uiPages: ['LMStudioPage'],
    runtimeConsumers: ['bot/src/ai/lmstudio.ts'],
    sourceOrder: ['env', 'db', 'default'],
  }),
  defineSetting({
    key: 'lmstudio_url_updated_at',
    label: 'LM Studio Heartbeat At',
    domain: 'lmstudio',
    visibility: 'derived',
    valueType: 'string',
    description: 'Timestamp heartbeat, записывается runtime.',
    uiPages: ['LMStudioPage'],
    runtimeConsumers: ['bot/src/ai/lmstudio.ts'],
    sourceOrder: ['runtime', 'db'],
  }),
  defineSetting({
    key: 'lmstudio_url_heartbeat_url',
    label: 'LM Studio Heartbeat URL',
    domain: 'lmstudio',
    visibility: 'derived',
    valueType: 'string',
    description: 'Нормализованный heartbeat URL, записывается runtime.',
    uiPages: ['LMStudioPage'],
    runtimeConsumers: ['bot/src/ai/lmstudio.ts'],
    sourceOrder: ['runtime', 'db'],
  }),
  defineSetting({
    key: 'digest_news_sites',
    label: 'Digest News Sites',
    domain: 'news',
    visibility: 'internal',
    valueType: 'json',
    description: 'JSON-конфигурация новостных сайтов для digest.',
    uiPages: ['NewsSourcesPage'],
    runtimeConsumers: ['bot/src/features/news-parser.ts', 'bot/src/features/digest-hybrid.ts'],
  }),
  defineSetting({
    key: '__healthcheck__',
    label: 'Healthcheck Marker',
    domain: 'system',
    visibility: 'internal',
    valueType: 'string',
    description: 'Служебный ключ проверки доступности settings backend.',
    uiPages: [],
    runtimeConsumers: ['bot/src/index.ts'],
  }),
  defineSetting({
    key: 'notes_soft_archive_registry',
    label: 'Notes Soft Archive Registry',
    domain: 'system',
    visibility: 'internal',
    valueType: 'json',
    description: 'Журнал soft-archive решений по notes reconciliation без изменения исторических note-документов.',
    uiPages: ['ReconciliationPage'],
    runtimeConsumers: ['bot/src/features/notes-repo.ts', 'bot/src/features/reconciliation/notes-reconciliation.ts'],
  }),
  defineSetting({
    key: 'reminder_delivery_registry',
    label: 'Reminder Delivery Registry',
    domain: 'system',
    visibility: 'internal',
    valueType: 'json',
    description: 'Реестр reminders, уже отправленных пользователю, но ещё не подтверждённых markCompleted в БД.',
    uiPages: [],
    runtimeConsumers: ['bot/src/reminders/reminder-scheduler.ts'],
  }),
];

export const SETTINGS_REGISTRY_MAP = new Map(
  SETTINGS_REGISTRY.map((entry) => [entry.key, entry]),
);

export function getSettingRegistryEntry(key: string): SettingRegistryEntry | null {
  return SETTINGS_REGISTRY_MAP.get(key) ?? null;
}

export function isKnownSettingKey(key: string): boolean {
  return SETTINGS_REGISTRY_MAP.has(key);
}
