import type { NewsSite } from '../../../shared/types/index.js';

const JAPAN_AI_KEYWORDS = [
  'AI',
  '生成AI',
  'バイブコーディング',
  'AIエージェント',
  'Copilot',
  'Cursor',
  'LLM',
];

const KOREA_AI_KEYWORDS = [
  'AI',
  '바이브 코딩',
  '생성형 AI',
  'AI 에이전트',
  '코딩 도구',
  'LLM',
  'Copilot',
  'Cursor',
];

const CHINA_AI_KEYWORDS = [
  'AI',
  '大模型',
  '开源模型',
  '微调',
  'AI编程',
  '代码生成',
  'AI 编程助手',
  '智能体',
  'RAG',
  'DeepSeek',
  'Qwen',
  'Copilot',
  'Cursor',
];

export const ASIA_NEWS_SOURCE_MANIFEST: NewsSite[] = [
  {
    name: 'ITmedia AI+',
    url: 'https://rss.itmedia.co.jp/rss/2.0/aiplus.xml',
    enabled: true,
    type: 'rss',
    category: 'asia_tech',
    language: 'ja',
    tier: 'tier1',
    filterKeywords: JAPAN_AI_KEYWORDS,
  },
  {
    name: '@IT',
    url: 'https://rss.itmedia.co.jp/rss/2.0/ait.xml',
    enabled: true,
    type: 'rss',
    category: 'asia_tech',
    language: 'ja',
    tier: 'tier1',
    filterKeywords: JAPAN_AI_KEYWORDS,
  },
  {
    name: 'Nikkei XTECH',
    url: 'https://xtech.nikkei.com/rss/xtech-it.rdf',
    enabled: true,
    type: 'rss',
    category: 'asia_tech',
    language: 'ja',
    tier: 'tier3',
    filterKeywords: JAPAN_AI_KEYWORDS,
  },
  {
    name: 'ASCII.jp',
    url: 'https://ascii.jp/rss.xml',
    enabled: true,
    type: 'rss',
    category: 'asia_tech',
    language: 'ja',
    tier: 'tier1',
    filterKeywords: JAPAN_AI_KEYWORDS,
  },
  {
    name: 'ZDNet Japan',
    url: 'https://japan.zdnet.com/',
    enabled: true,
    type: 'rss',
    category: 'asia_tech',
    language: 'ja',
    tier: 'tier1',
    filterKeywords: JAPAN_AI_KEYWORDS,
  },
  {
    name: 'AISmiley',
    url: 'https://aismiley.co.jp/ai_news/',
    enabled: true,
    type: 'html_scrape',
    category: 'asia_tech',
    language: 'ja',
    tier: 'tier2',
    filterKeywords: JAPAN_AI_KEYWORDS,
    htmlMapping: {
      itemSelectors: ['article', '.bl_postsUnit_item', '.p-postList__item', '.c-card'],
      titleSelectors: ['h2', 'h3', '.entry-title', '.c-card__title', 'a'],
      linkSelectors: ['a[href]'],
      removeSelectors: ['nav', 'footer', '.breadcrumb', '.pagination'],
    },
  },
  {
    name: 'Tech+ (Mynavi)',
    url: 'https://news.mynavi.jp/techplus/',
    enabled: true,
    type: 'rss',
    category: 'asia_tech',
    language: 'ja',
    tier: 'tier1',
    filterKeywords: JAPAN_AI_KEYWORDS,
  },
  {
    name: 'THE BRIDGE',
    url: 'https://thebridge.jp/feed',
    enabled: true,
    type: 'rss',
    category: 'asia_tech',
    language: 'ja',
    tier: 'tier1',
    filterKeywords: JAPAN_AI_KEYWORDS,
  },
  {
    name: 'TechCrunch Japan',
    url: 'https://jp.techcrunch.com/feed/',
    enabled: true,
    type: 'rss',
    category: 'asia_tech',
    language: 'ja',
    tier: 'tier1',
    filterKeywords: JAPAN_AI_KEYWORDS,
  },
  {
    name: 'Impress Watch',
    url: 'https://www.watch.impress.co.jp/data/rss/1.0/ipw/feed.rdf',
    enabled: true,
    type: 'rss',
    category: 'asia_tech',
    language: 'ja',
    tier: 'tier1',
    filterKeywords: JAPAN_AI_KEYWORDS,
  },
  {
    name: 'vibecode.tokyo',
    url: 'https://vibecode.tokyo/',
    enabled: true,
    type: 'html_scrape',
    category: 'asia_tech',
    language: 'ja',
    tier: 'tier2',
    filterKeywords: JAPAN_AI_KEYWORDS,
    htmlMapping: {
      itemSelectors: ['article', '.post', '.entry', '.blog-entry'],
      titleSelectors: ['h1', 'h2', 'h3', '.entry-title', 'a'],
      linkSelectors: ['a[href]'],
      removeSelectors: ['nav', 'footer', '.pagination'],
    },
  },
  {
    name: 'PR Times (Vibe Coding)',
    url: 'https://prtimes.jp/main/html/searchrlp/company_id/0?kw=%E3%83%90%E3%82%A4%E3%83%96%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0',
    enabled: true,
    type: 'html_scrape',
    category: 'asia_tech',
    language: 'ja',
    tier: 'tier2',
    filterKeywords: JAPAN_AI_KEYWORDS,
    htmlMapping: {
      itemSelectors: ['article', '.list-article', '.release_list_item', '.search-result-item'],
      titleSelectors: ['h2', 'h3', '.list-article__title', '.release_list_item_ttl', 'a'],
      linkSelectors: ['a[href]'],
      removeSelectors: ['nav', 'footer', '.pager', '.pagination'],
    },
  },
  {
    name: 'Zenn.dev (AI)',
    url: 'https://zenn.dev/topics/ai/feed',
    enabled: true,
    type: 'rss',
    category: 'asia_tech',
    language: 'ja',
    tier: 'tier1',
    filterKeywords: JAPAN_AI_KEYWORDS,
  },
  {
    name: 'Zenn.dev (LLM)',
    url: 'https://zenn.dev/topics/llm/feed',
    enabled: true,
    type: 'rss',
    category: 'asia_tech',
    language: 'ja',
    tier: 'tier1',
    filterKeywords: JAPAN_AI_KEYWORDS,
  },
  {
    name: 'Zenn.dev (VibeCoding)',
    url: 'https://zenn.dev/topics/vibecoding/feed',
    enabled: true,
    type: 'rss',
    category: 'asia_tech',
    language: 'ja',
    tier: 'tier1',
    filterKeywords: JAPAN_AI_KEYWORDS,
  },
  {
    name: 'Qiita (AI)',
    url: 'https://qiita.com/api/v2/items?query=title:AI+OR+title:LLM+OR+title:ChatGPT+OR+title:GPT+OR+title:Copilot+OR+title:Cursor&per_page=60',
    enabled: true,
    type: 'json_api',
    category: 'asia_tech',
    language: 'ja',
    tier: 'tier1',
    jsonMapping: {
      itemsPath: '',
      titleField: 'title',
      urlField: 'url',
      dateField: 'created_at',
    },
    filterKeywords: JAPAN_AI_KEYWORDS,
  },
  {
    name: 'GeekNews',
    url: 'https://news.hada.io/',
    enabled: true,
    type: 'html_scrape',
    category: 'asia_tech',
    language: 'ko',
    tier: 'tier2',
    filterKeywords: KOREA_AI_KEYWORDS,
    htmlMapping: {
      itemSelectors: ['.topic_row', 'article', '.topic-item', '.news-item'],
      titleSelectors: ['.topictitle', 'h2', 'h3', 'a'],
      linkSelectors: ['a[href]'],
      removeSelectors: ['nav', 'footer', '.pagination'],
    },
  },
  {
    name: 'KoreaTechToday',
    url: 'https://www.koreatechtoday.com/feed/',
    enabled: true,
    type: 'rss',
    category: 'asia_tech',
    language: 'ko',
    tier: 'tier1',
    filterKeywords: KOREA_AI_KEYWORDS,
  },
  {
    name: 'KoreaTechDesk',
    url: 'https://www.koreatechdesk.com/feed/',
    enabled: true,
    type: 'rss',
    category: 'asia_tech',
    language: 'ko',
    tier: 'tier1',
    filterKeywords: KOREA_AI_KEYWORDS,
  },
  {
    name: 'Yonhap News',
    url: 'https://en.yna.co.kr/',
    enabled: true,
    type: 'rss',
    category: 'asia_tech',
    language: 'ko',
    tier: 'tier1',
    filterKeywords: KOREA_AI_KEYWORDS,
  },
  {
    name: 'WOWTALE',
    url: 'https://en.wowtale.net/feed/',
    enabled: true,
    type: 'rss',
    category: 'asia_tech',
    language: 'ko',
    tier: 'tier1',
    filterKeywords: KOREA_AI_KEYWORDS,
  },
  {
    name: 'AI Matters Korea',
    url: 'https://aimatters.co.kr/news-report/',
    enabled: true,
    type: 'html_scrape',
    category: 'asia_tech',
    language: 'ko',
    tier: 'tier2',
    filterKeywords: KOREA_AI_KEYWORDS,
    htmlMapping: {
      itemSelectors: ['article', '.news-item', '.post', '.entry'],
      titleSelectors: ['h2', 'h3', '.entry-title', 'a'],
      linkSelectors: ['a[href]'],
      removeSelectors: ['nav', 'footer', '.pagination'],
    },
  },
  {
    name: 'ETNews',
    url: 'https://www.etnews.com/news/section.html?id1=02',
    enabled: true,
    type: 'html_scrape',
    category: 'asia_tech',
    language: 'ko',
    tier: 'tier2',
    filterKeywords: KOREA_AI_KEYWORDS,
  },
  {
    name: 'NewsTomato',
    url: 'https://www.newstomato.com/search?keyword=AI',
    enabled: true,
    type: 'html_scrape',
    category: 'asia_tech',
    language: 'ko',
    tier: 'tier3',
    filterKeywords: KOREA_AI_KEYWORDS,
  },
  {
    name: 'Naver News Search',
    url: 'https://search.naver.com/search.naver?where=news&query=%EB%B0%94%EC%9D%B4%EB%B8%8C+%EC%BD%94%EB%94%A9+OR+%EC%83%9D%EC%84%B1%ED%98%95+AI+OR+AI+%EC%97%90%EC%9D%B4%EC%A0%84%ED%8A%B8',
    enabled: true,
    type: 'html_scrape',
    category: 'asia_tech',
    language: 'ko',
    tier: 'tier3',
    filterKeywords: KOREA_AI_KEYWORDS,
  },
  {
    name: 'Daum News Search',
    url: 'https://search.daum.net/search?w=news&q=%EB%B0%94%EC%9D%B4%EB%B8%8C%20%EC%BD%94%EB%94%A9',
    enabled: true,
    type: 'html_scrape',
    category: 'asia_tech',
    language: 'ko',
    tier: 'tier3',
    filterKeywords: KOREA_AI_KEYWORDS,
  },
  {
    name: '机器之心 (RSSHub)',
    url: 'https://rsshub.app/wechat/mp/jiqizhixin',
    enabled: true,
    type: 'rss',
    category: 'asia_tech',
    language: 'zh',
    tier: 'tier1',
    filterKeywords: CHINA_AI_KEYWORDS,
  },
  {
    name: '量子位 (RSSHub)',
    url: 'https://rsshub.app/wechat/mp/QbitAI',
    enabled: true,
    type: 'rss',
    category: 'asia_tech',
    language: 'zh',
    tier: 'tier1',
    filterKeywords: CHINA_AI_KEYWORDS,
  },
  {
    name: '新智元 (RSSHub)',
    url: 'https://rsshub.app/wechat/mp/aiera',
    enabled: true,
    type: 'rss',
    category: 'asia_tech',
    language: 'zh',
    tier: 'tier1',
    filterKeywords: CHINA_AI_KEYWORDS,
  },
  {
    name: '36kr AI News',
    url: 'https://36kr.com/feed',
    enabled: true,
    type: 'rss',
    category: 'asia_tech',
    language: 'zh',
    tier: 'tier1',
    filterKeywords: CHINA_AI_KEYWORDS,
  },
  {
    name: 'InfoQ China',
    url: 'https://www.infoq.cn/feed',
    enabled: true,
    type: 'rss',
    category: 'asia_tech',
    language: 'zh',
    tier: 'tier1',
    filterKeywords: CHINA_AI_KEYWORDS,
  },
  {
    name: 'CSDN AI Search',
    url: 'https://so.csdn.net/so/search?q=AI%E7%BC%96%E7%A8%8B',
    enabled: true,
    type: 'html_scrape',
    category: 'asia_tech',
    language: 'zh',
    tier: 'tier2',
    filterKeywords: CHINA_AI_KEYWORDS,
  },
  {
    name: 'Zhihu Search',
    url: 'https://www.zhihu.com/search?type=content&q=AI%E7%BC%96%E7%A8%8B',
    enabled: true,
    type: 'html_scrape',
    category: 'asia_tech',
    language: 'zh',
    tier: 'tier3',
    filterKeywords: CHINA_AI_KEYWORDS,
  },
  {
    name: 'Bilibili AI Search',
    url: 'https://search.bilibili.com/all?keyword=AI%E7%BC%96%E7%A8%8B',
    enabled: true,
    type: 'html_scrape',
    category: 'asia_tech',
    language: 'zh',
    tier: 'tier3',
    filterKeywords: CHINA_AI_KEYWORDS,
  },
  {
    name: 'Toutiao AI Search',
    url: 'https://so.toutiao.com/search?dvpf=pc&keyword=AI%E7%BC%96%E7%A8%8B',
    enabled: true,
    type: 'html_scrape',
    category: 'asia_tech',
    language: 'zh',
    tier: 'tier3',
    filterKeywords: CHINA_AI_KEYWORDS,
  },
  {
    name: 'Baidu Wenxin Search',
    url: 'https://www.baidu.com/s?wd=%E6%96%87%E5%BF%83+AI%E7%BC%96%E7%A8%8B',
    enabled: true,
    type: 'html_scrape',
    category: 'asia_tech',
    language: 'zh',
    tier: 'tier3',
    filterKeywords: CHINA_AI_KEYWORDS,
  },
  {
    name: 'Pandaily',
    url: 'https://pandaily.com/feed',
    enabled: true,
    type: 'rss',
    category: 'asia_tech',
    language: 'en',
    tier: 'tier1',
    filterKeywords: CHINA_AI_KEYWORDS,
  },
  {
    name: 'TechNode',
    url: 'https://technode.com/feed',
    enabled: true,
    type: 'rss',
    category: 'asia_tech',
    language: 'en',
    tier: 'tier1',
    filterKeywords: CHINA_AI_KEYWORDS,
  },
  {
    name: 'ChinAI Newsletter',
    url: 'https://chinai.substack.com/feed',
    enabled: true,
    type: 'rss',
    category: 'asia_tech',
    language: 'en',
    tier: 'tier1',
    filterKeywords: CHINA_AI_KEYWORDS,
  },
  {
    name: 'Recode China AI',
    url: 'https://recodechinaai.substack.com/feed',
    enabled: true,
    type: 'rss',
    category: 'asia_tech',
    language: 'en',
    tier: 'tier1',
    filterKeywords: CHINA_AI_KEYWORDS,
  },
  {
    name: 'CAC',
    url: 'https://www.cac.gov.cn/',
    enabled: true,
    type: 'html_scrape',
    category: 'asia_tech',
    language: 'zh',
    tier: 'tier3',
    filterKeywords: CHINA_AI_KEYWORDS,
  },
];

export const ASIA_NEWS_SOURCE_PRESET_COUNT = ASIA_NEWS_SOURCE_MANIFEST.length;
