export type { NewsSite, ParsedHeadline, NewsPresetGroup } from './news/index.js';

export {
  DEFAULT_AI_TECH_SOURCES,
  assertNewsSiteUrlIsSafe,
  normalizeNewsSite,
  normalizeNewsSites,
  canonicalizeHeadlineUrl,
  buildHeadlineFingerprint,
  getPresetSources,
  getPresetSourceCounts,
  mergeNewsSites,
  getConfiguredSites,
  saveConfiguredSites,
  clearParsedNewsCache,
  parseNewsFromSite,
  dedupeParsedHeadlines,
  groupHeadlinesByCategory,
  countMergedDuplicates,
  filterByCategory,
  filterByLanguage,
  setNewsParsingKilled,
  isNewsParsingKilled,
  parseAllConfiguredSites,
} from './news/index.js';
